// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euvguvntujkerezwbzwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dmd1dm50dWprZXJlendiend6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjU4NTYsImV4cCI6MjA2OTI0MTg1Nn0.ws4PZyZA-kevHtSghlOVE617dY3iY1av2Z4wDQu1r18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});